# Generated by Django 2.0.1 on 2020-02-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
