# Generated by Django 2.0.1 on 2020-02-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': True},
        ),
    ]
