# Generated by Django 2.0.1 on 2020-02-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200210_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={},
        ),
    ]
